<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>SLAYER_RoundEndSound</AssemblyName>
    <OutputPath>$(MSBuildThisFileDirectory)build/</OutputPath>
    <PublishDir>$(OutputPath)publish/SLAYER_RoundEndSound</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="*" />
    <PackageReference Include="Dommel" Version="*" />
    <PackageReference Include="FluentMigrator" Version="*" />
    <PackageReference Include="FluentMigrator.Runner.MySql" Version="*" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="*" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="*" />
    <PackageReference Include="MySqlConnector" Version="*" />
    <PackageReference Include="Npgsql" Version="*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="SwiftlyS2.CS2" Version="*-*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="SwiftlyS2.Plugin.Audio.API" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources/gamedata/**/*;resources/templates/**/*;resources/translations/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="examples\**\*.cs" />
  </ItemGroup>

  <Target Name="CreateZip" AfterTargets="Publish">
    <ItemGroup>
      <PublishFiles Include="$(PublishDir)**\*.*" />
    </ItemGroup>
    
    <ZipDirectory SourceDirectory="$(PublishDir)../" DestinationFile="$(OutputPath)../$(AssemblyName).zip" Overwrite="true" />
  </Target>

</Project> 
